/**
 * Type augmentation for CloudflareEnv.
 *
 * `cloudflare-env.d.ts` is regenerated by `wrangler types` (npm run
 * cf-typegen) and only includes vars/secrets currently bound on the
 * deployed worker. That means a freshly-added secret isn't in the
 * generated type until after `wrangler secret put X` runs against
 * the live worker — which would block PRs that add new secret-using
 * code from passing CI.
 *
 * This file declares the secrets/vars that the code expects to exist
 * at runtime. Wrangler `secret list` is still the source of truth at
 * deploy time (a typo in a name here won't auto-fix a missing secret);
 * this just keeps TypeScript happy until the secret lands.
 *
 * If you add a new var/secret:
 *   1. Add the declaration here
 *   2. Run `wrangler secret put <NAME>` (or add to wrangler.jsonc vars)
 *   3. Optionally run `npm run cf-typegen` after the secret is set
 *      to make this augmentation redundant (safe to leave either way)
 */
interface CloudflareEnv {
  // Stripe — added in chore/stripe-plumbing (PR #14).
  // Set via `wrangler secret put STRIPE_SECRET_KEY` (sk_test_* / sk_live_*)
  // and `wrangler secret put STRIPE_WEBHOOK_SECRET` (whsec_*).
  // NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY lives in wrangler.jsonc vars and
  // is auto-picked-up by cf-typegen.
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
}
