import { generateCommentary } from "@/lib/commentary/generate";
import type { ScoreResult } from "@/lib/scoring";

export default async function Commentary({ scoreResult }: { scoreResult: ScoreResult }) {
  const text = await generateCommentary(scoreResult);
  if (!text) return null;

  return (
    <section className="commentary-card" aria-label="Score analysis">
      <div className="commentary-label">QScore Analysis</div>
      <p className="commentary-text">{text}</p>
      <div className="commentary-attribution">
        Generated by AI from the underlying QScore factors. Not investment advice.
      </div>
    </section>
  );
}

export function CommentarySkeleton() {
  return (
    <section className="commentary-card commentary-skeleton-card" aria-label="Loading analysis">
      <div className="commentary-label">QScore Analysis</div>
      <div className="commentary-skeleton">
        <div className="line" style={{ width: "92%" }} />
        <div className="line" style={{ width: "88%" }} />
        <div className="line" style={{ width: "76%" }} />
        <div className="line" style={{ width: "64%" }} />
      </div>
    </section>
  );
}
