import { generateCommentary } from "@/lib/commentary/generate";
import { fallbackCommentary } from "@/lib/commentary/fallback";
import type { ScoreResult } from "@/lib/scoring";

export default async function Commentary({ scoreResult }: { scoreResult: ScoreResult }) {
  // Try the AI-generated paragraph first. When it returns null (binding
  // unavailable, model timeout, capacity error) we fall back to a
  // deterministic structured-text commentary so every score page has unique
  // body text. Without this, crawlers were seeing the heading but no
  // paragraph — a thin-content signal we want to avoid.
  const aiText = await generateCommentary(scoreResult);
  const text = aiText ?? fallbackCommentary(scoreResult);
  const isFallback = aiText === null;

  return (
    <section className="commentary-card" aria-label="Score analysis">
      <div className="commentary-label">QScore Analysis</div>
      <p className="commentary-text">{text}</p>
      <div className="commentary-attribution">
        {isFallback
          ? "Generated from the underlying QScore factors. Not investment advice."
          : "Generated by AI from the underlying QScore factors. Not investment advice."}
      </div>
    </section>
  );
}

export function CommentarySkeleton() {
  return (
    <section className="commentary-card commentary-skeleton-card" aria-label="Loading analysis">
      <div className="commentary-label">QScore Analysis</div>
      <div className="commentary-skeleton">
        <div className="line" style={{ width: "92%" }} />
        <div className="line" style={{ width: "88%" }} />
        <div className="line" style={{ width: "76%" }} />
        <div className="line" style={{ width: "64%" }} />
      </div>
    </section>
  );
}
