"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

// Reads the tier-gated narrative from /api/narratives/:ticker (a `private,
// no-store` endpoint — never edge-cached, so free/paid bodies can't cross
// users). The server decides which sections are visible; this component renders
// what it receives and shows a locked teaser + upgrade CTA for gated sections.

const DISCLAIMER = "Generated by AI from QScoring data. Not investment advice.";

const PARAGRAPH_SECTIONS = [
  { key: "financial_health", label: "Financial Health" },
  { key: "competitive_position", label: "Competitive Position" },
  { key: "factor_macro_profile", label: "Factor & Macro Profile" },
] as const;

const LIST_SECTIONS = [
  { key: "risk_flags", label: "Risk Flags" },
  { key: "catalyst_watch", label: "Catalyst Watch" },
] as const;

const GATED_LABELS: Record<string, string> = {
  competitive_position: "Competitive Position",
  factor_macro_profile: "Factor & Macro Profile",
  risk_flags: "Risk Flags",
  catalyst_watch: "Catalyst Watch",
  one_line_summary: "Summary",
};

type Narrative = {
  financial_health?: string;
  competitive_position?: string;
  factor_macro_profile?: string;
  risk_flags?: string[];
  catalyst_watch?: string[];
  one_line_summary?: string;
};

type ApiResponse = {
  status: "ok" | "empty" | "error" | "invalid";
  tier?: "free" | "pro";
  dataAsOf?: string;
  narrative?: Narrative;
  gated?: boolean;
  gatedSections?: string[];
};

function fmtDate(iso: string): string {
  return new Date(`${iso}T12:00:00Z`).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}

export default function QScoreAIAnalysis({ ticker }: { ticker: string }) {
  const [data, setData] = useState<ApiResponse | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setData(null);
    setFailed(false);
    fetch(`/api/narratives/${encodeURIComponent(ticker)}`)
      .then((r) => r.json() as Promise<ApiResponse>)
      .then((d) => {
        if (!cancelled) setData(d);
      })
      .catch(() => {
        if (!cancelled) setFailed(true);
      });
    return () => {
      cancelled = true;
    };
  }, [ticker]);

  if (failed) return null;

  if (!data) {
    return (
      <section className="qai-card" aria-label="QScore AI Analysis">
        <div className="qai-head">
          <span className="section-eyebrow">QScore AI Analysis</span>
        </div>
        <div className="qai-skeleton" />
      </section>
    );
  }

  const asOf = data.dataAsOf ? fmtDate(data.dataAsOf) : null;

  // Clean empty state — a narrative hasn't been generated for this ticker yet.
  if (data.status !== "ok" || !data.narrative) {
    return (
      <section className="qai-card" aria-label="QScore AI Analysis">
        <div className="qai-head">
          <span className="section-eyebrow">QScore AI Analysis</span>
          <h2 className="section-title">AI Analysis</h2>
        </div>
        <p className="qai-empty">
          An AI briefing for {ticker} hasn&apos;t been generated yet. These are produced from
          QScoring&apos;s own data on a weekly cadence — check back soon.
        </p>
        <div className="qai-footer">{DISCLAIMER}</div>
      </section>
    );
  }

  const n = data.narrative;
  const asOfChip = asOf ? <span className="qai-asof">As of {asOf}</span> : null;

  return (
    <section className="qai-card" aria-label="QScore AI Analysis">
      <div className="qai-head">
        <span className="section-eyebrow">QScore AI Analysis</span>
        <h2 className="section-title">AI Analysis</h2>
      </div>

      {n.one_line_summary && (
        <p className="qai-summary">
          {n.one_line_summary}
          {asOfChip}
        </p>
      )}

      {PARAGRAPH_SECTIONS.map(({ key, label }) =>
        n[key] ? (
          <div className="qai-section" key={key}>
            <div className="qai-section-head">
              <h3 className="qai-section-title">{label}</h3>
              {asOfChip}
            </div>
            <p className="qai-text">{n[key] as string}</p>
          </div>
        ) : null
      )}

      {LIST_SECTIONS.map(({ key, label }) => {
        const items = n[key] as string[] | undefined;
        return items && items.length ? (
          <div className="qai-section" key={key}>
            <div className="qai-section-head">
              <h3 className="qai-section-title">{label}</h3>
              {asOfChip}
            </div>
            <ul className="qai-list">
              {items.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          </div>
        ) : null;
      })}

      {data.gated && data.gatedSections && data.gatedSections.length > 0 && (
        <div className="qai-locked">
          <div className="qai-locked-head">
            <span aria-hidden="true">🔒</span> Unlock the full AI analysis
          </div>
          <p className="qai-locked-body">
            {data.gatedSections.map((s) => GATED_LABELS[s] ?? s).join(", ")} are available on a paid plan.
          </p>
          <Link href="/pricing" className="qai-upgrade">
            See plans
          </Link>
        </div>
      )}

      <div className="qai-footer">{DISCLAIMER}</div>
    </section>
  );
}

export function QScoreAIAnalysisSkeleton() {
  return (
    <section className="qai-card" aria-label="QScore AI Analysis">
      <div className="qai-head">
        <span className="section-eyebrow">QScore AI Analysis</span>
      </div>
      <div className="qai-skeleton" />
    </section>
  );
}
